{% set name = "podaacpy" %}
{% set version = "2.2.0" %}
{% set sha256 = "10eef2c61905f03a7db2ed601ce88b57855187057bf09ce6dc9f0b0020c79650" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [not py36]
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - beautifulsoup4
    - future
    - requests

test:
  imports:
    - podaac

about:
  home: https://github.com/nasa/podaacpy
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A python utility library for interacting with NASA JPLs PO.DAAC'
  doc_url: http://podaacpy.readthedocs.org/en/latest/

extra:
  recipe-maintainers:
    - agoodm
    - lewismc
