{% set version = "2.3.0" %}

package:
  name: podaacpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/podaacpy/podaacpy-{{ version }}.tar.gz
  sha256: c689f3824df4ec92d5025486084f5e3d35bc3c7e4dad9a6532dfd036cc28fcc3


build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - beautifulsoup4
    - configparser
    - defusedxml
    - future
    - pathlib2
    - requests

test:
  imports:
    - podaac
  requires:
    - nose
  commands:
    - nosetests --verbosity=3

about:
  home: https://github.com/nasa/podaacpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A python utility library for interacting with NASA JPLs PO.DAAC'
  doc_url: http://podaacpy.readthedocs.org/en/latest/

extra:
  recipe-maintainers:
    - agoodm
    - lewismc
    - noah-de 
