appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: zJeNkl2W+BxfHej3jTTUUDmbh+vFSHVlc6k95O+OEW1hVVun0zTh6KRQ9ictuwhOIis8Y9oamUoQFn5CblmrbNeEDw2qw1TxBdIecefs0MabZHcb1DD0ti2HKhdANFr/EAiFqLqXZfRiNlwyMLsBrokz3BYB/rKr4xsXS6iz/C3SCJZ3Wpk/mvlVDwur0qDO/JR9ckAU9qySZGAdwQIcRWaFVQlN0t3bPThjPQV04wPPB6+VH0UPAZwlMmbGj2Vn+oaZKvUFg+NNn2DLapgdacyDThSfsybH31wvCcDYSxah9zSdKmYIyUwZT++eKcFOcB0Oy/aolHJ0oNdJpUn9E0ZihUQPF7aHb+yDjtq8vvGJKXxGZpt1SKQwNvriijUsh3UhetJlWLYNxtKskg6nzPYxDnbno+PpGHNoSG6RqODB9MO3+NqkrWAoJNWIXd5bqzvWkB5jg9fpINHO4/UEzQQ8sHQ7/E6ZUoQX/YUmIKA8B9a+avqy+5oaCpg1F3o3NIF20Kgnj2XdQ0zZhsBXnhcx704iaGeh88xBSnhJKx1ObJTjZoijr5OEGEnNM/cogRcOhXmr6//Upnma0CIF83kRsfp+KvaqwN7dOG0PBLFKlydCYu+AtcAgYrUPCaK7rsOcB1eR5kTsJi0/qNGmEFZPk9k25Wb0f7++j/MXSfE=}
