travis:
  secure:
    BINSTAR_TOKEN: lE0QT90wuTtsN3qrVJ7HWFgMU5IiTgQrLRWXfCuFkesIRbypRQeidJhnh603nTq1flR6WJmEBUo/Sm+bwervPp7JHEahD4F7cTc4l+yZ2+rRq2K/sXDye/nQTMurKQWY5G5NcMn7C+8Wj4Fs89JquqDCc6wwUVF0x5N2TY5BNiAL9qNODj6y9EJILbYDZdM0+czgAbZEYditQ68052Lm0Gt+MUcvbUM9dsr/RWIdI6IVo1CbhwbolnHerlpmeByZLQiT408xH8+4jYRj84HHAVIQZfXRmuSKXBRf8HIdk8AjULfPZf4DTsKmrFwT1BISIpAcWFt+gojWTnJ/E5zqEzbTjs7Cha8XaamK9QYs/o9j6rUsJ/OtLZRR5nx2SDfyHL1e8eVis4mJP7kmcQptWwVvf/pfF17UZpcg1i90fmCi8BXx1I7DYWimB5oLmyxj+eVUTC7KdjliiqGLCYDgXWrMpTKRFtN0NIfWkpvqHZ3QdYxbEWYEhYhyfm1M1ihVA+Edjw+h7qtiK5cwaB6hXqXNwTbK0VJ/B97UnUTunQyq6X1gg3LUbxmMHoJX5AVdBLYoQYB7LZNDDx/CqnYgDZiEB77kgz2hmqLN3zFlGErvmSWw1W5Km1JkSLYl0UUZUf35kVoHZ9gDIRqoMXUkJaYTjo3Lxd/YM0bqzwmgbFo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
